import type { ActivityItem, Gig, Mission, RewardsState } from "./types";

export const EARNINGS = {
  weekTotal: 86.5,
  available: 42.25,
  pending: 44.25,
  deliveriesThisWeek: 4,
  nextPayout: "Fri • 2–3 business days",
};

export const MISSIONS: Mission[] = [
  { id: "verify", title: "Verify your profile", rewardLabel: "+$5", status: "Completed", icon: "shield-checkmark-outline", onTap: "verify" },
  { id: "payout", title: "Add payout method", rewardLabel: "Unlock", status: "Not started", icon: "card-outline", onTap: "payout" },
  { id: "first_pickup", title: "Complete your first pickup", rewardLabel: "+$18", status: "In progress", icon: "car-outline", onTap: "gigs" },
  { id: "refer", title: "Refer a friend", rewardLabel: "+$10", status: "Not started", icon: "people-outline", onTap: "rewards" },
];

export const RECENT_ACTIVITY: ActivityItem[] = [
  { id: "a1", text: "Pickup completed", amountLabel: "+$18", when: "Today 2:41pm" },
  { id: "a2", text: "Referral bonus", amountLabel: "+$10", when: "Yesterday" },
  { id: "a3", text: "Cash out", amountLabel: "-$40", when: "Processing" },
  { id: "a4", text: "Delivery tip", amountLabel: "+$4", when: "Dec 31" },
  { id: "a5", text: "Pickup completed", amountLabel: "+$16.50", when: "Dec 30" },
];

export const REWARDS: RewardsState = {
  referralCode: "HAULSY-WES-21",
  invited: 2,
  completed: 1,
  streakTitle: "Complete 3 deliveries this week: +$15",
  streakProgress: 2 / 3,
};

export const GIGS: Gig[] = [
  {
    id: "g1",
    payout: 38,
    estGas: 6.4,
    net: 31.6,
    distanceToPickupKm: 2.1,
    pickupArea: "Surrey Central",
    dropoffArea: "Guildford",
    routeLabel: "Pickup: Surrey Central → Dropoff: Guildford",
    itemSize: "Medium",
    vehicleFit: "Sedan ok",
    etaMins: 28,
    heavy: false,
    twoPersonLift: false,
    routeDistanceKm: 18.2,
    state: "Available",
  },
  {
    id: "g2",
    payout: 52,
    estGas: 9.15,
    net: 42.85,
    distanceToPickupKm: 4.8,
    pickupArea: "Metrotown",
    dropoffArea: "Mount Pleasant",
    routeLabel: "Pickup: Metrotown → Dropoff: Mount Pleasant",
    itemSize: "Large",
    vehicleFit: "SUV recommended",
    etaMins: 44,
    heavy: true,
    twoPersonLift: true,
    routeDistanceKm: 26.0,
    state: "Available",
  },
  {
    id: "g3",
    payout: 24,
    estGas: 3.1,
    net: 20.9,
    distanceToPickupKm: 1.2,
    pickupArea: "Kitsilano",
    dropoffArea: "Downtown",
    routeLabel: "Pickup: Kitsilano → Dropoff: Downtown",
    itemSize: "Small",
    vehicleFit: "Sedan ok",
    etaMins: 22,
    heavy: false,
    twoPersonLift: false,
    routeDistanceKm: 11.4,
    state: "Available",
  },
  {
    id: "g4",
    payout: 61,
    estGas: 10.5,
    net: 50.5,
    distanceToPickupKm: 6.9,
    pickupArea: "Coquitlam",
    dropoffArea: "Richmond",
    routeLabel: "Pickup: Coquitlam → Dropoff: Richmond",
    itemSize: "Large",
    vehicleFit: "Truck required",
    etaMins: 58,
    heavy: true,
    twoPersonLift: true,
    routeDistanceKm: 31.8,
    state: "Available",
  },
  {
    id: "g5",
    payout: 29,
    estGas: 4.6,
    net: 24.4,
    distanceToPickupKm: 3.3,
    pickupArea: "Burnaby",
    dropoffArea: "New West",
    routeLabel: "Pickup: Burnaby → Dropoff: New West",
    itemSize: "Medium",
    vehicleFit: "Sedan ok",
    etaMins: 30,
    heavy: false,
    twoPersonLift: false,
    routeDistanceKm: 14.9,
    state: "Available",
  },
  {
    id: "g6",
    payout: 45,
    estGas: 7.2,
    net: 37.8,
    distanceToPickupKm: 2.7,
    pickupArea: "Commercial",
    dropoffArea: "Yaletown",
    routeLabel: "Pickup: Commercial → Dropoff: Yaletown",
    itemSize: "Medium",
    vehicleFit: "SUV recommended",
    etaMins: 36,
    heavy: true,
    twoPersonLift: false,
    routeDistanceKm: 20.3,
    state: "Available",
  },
];

